Creating example tests
bazelbuild/examples pull request #232
Opened 2021-12-15 04:38 UTC by KilimAnnejaro

Per https://github.com/bazelbuild/bazel/pull/14432#issuecomment-994278938, adding example testing code to the sample repo.

@aiuto not sure if this is what you were looking for?

2021-12-16 03:46 UTC, KilimAnnejaro commented
@aiuto @brandjon @c-parsons bump?

2021-12-24 17:37 UTC, aiuto reviewed
I'm going to pass this to someone who knows more about maven than I do. I never go near it if I can avoid it.

2021-12-24 17:37 UTC, aiuto commented on java-tutorial/BUILD
> +    name = "java-maven-lib",
Why java-*maven*-lib?  Isn't it just calculator_lib?

2021-12-24 17:37 UTC, aiuto commented on java-tutorial/BUILD
>      srcs = glob(["src/main/java/com/example/*.java"]),
Doesn't this have to exclude ProjectRunner.java?

2021-12-24 17:41 UTC, aiuto commented
Do we have a standard way to include junit without having to bring in maven
as well?
That would make a better example because it does not conflate java_test
with maven.

On Wed, Dec 15, 2021 at 10:47 PM Anne E. Ulrich ***@***.***>
wrote:

> @aiuto <https://github.com/aiuto> @brandjon <https://github.com/brandjon>
> @c-parsons <https://github.com/c-parsons> bump?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/examples/pull/232#issuecomment-995413420>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXHHHDEMB2TQZNANZHNSDLURFOLTANCNFSM5KCUTGKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2022-01-19 08:29 UTC, jin requested changes
Thanks for your contribution!

This repo is used with https://docs.bazel.build/versions/main/tutorial/java.html. The BUILD file doesn't have the greeter target for that reason, because the instructions wants the user to add it manually. So I don't think we should change the contents of this repo at all, unless there's an intention to update the java tutorial on docs.bazel.build in tandem.

Also, there are already Junit + rules_jvm_external test examples in https://github.com/bazelbuild/examples/tree/main/java-maven (see https://github.com/bazelbuild/examples/blob/d1a1f1fcf460a7f3aa0eb845b22dab061eff8ec9/java-maven/BUILD#L17), so I'm not sure what this PR is adding.

2022-01-19 08:29 UTC, jin commented on java-tutorial/BUILD
> +    srcs = ["src/main/java/com/example/Greeting.java"],
This doesn't exist..?

2023-04-05 03:12 UTC, aiuto commented
Going back to Jin's comment. This is part of the tutorial, so we don't want to change it without changing the tutorial in concert. I'm going to close this because it is so stale and someone can start again if they want to overhaul the whole tutorial.

2023-04-05 03:12 UTC, closed without merging